apiVersion: v1
kind: Service
metadata:
  name: scpi-doc-validation-front
spec:
  selector:
    app: scpi-doc-validation-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP